### PR TITLE
rspec and capybara setup

### PR DESCRIPTION
**Pull request by szmo**
https://trello.com/c/hGnryttz/3-setup-gem%C3%B3w-dla-test%C3%B3w

### CODE REVIEW

**Comment by szmo** [comment]
[Setup gemów dla testów](https://trello.com/c/hGnryttz/3-setup-gem%C3%B3w-dla-test%C3%B3w)

**Review by evemorgen — CHANGES_REQUESTED** [review]
Please provide some sort of proof that it actually works, like some basic test run as:
```
def test_simple
    assert(true)
  end
```
or sth similar

**Comment by szmo** [comment]
screen shot 2017-11-05 at 21 53 03

**Comment by evemorgen** [comment]
seems legit to me now

**Review by evemorgen — APPROVED** [review]

**Pull request merged**
